name: CI-CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker asia-south1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devops-repo/devops-http-app:${{ github.sha }} .
        docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devops-repo/devops-http-app:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy devops-http-app \
          --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devops-repo/devops-http-app:${{ github.sha }} \
          --region ${{ secrets.REGION }} \
          --platform managed \
          --allow-unauthenticated
